In [1]:
import pandas as pd

In [2]:
medquad_df = pd.read_csv('medquad.csv')

In [3]:
medquad_df

,question,answer,source,focus_area
0,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...,NIHSeniorHealth,Glaucoma
1,What causes Glaucoma ?,"Nearly 2.7 million people have glaucoma, a lea...",NIHSeniorHealth,Glaucoma
2,What are the symptoms of Glaucoma ?,Symptoms of Glaucoma Glaucoma can develop in ...,NIHSeniorHealth,Glaucoma
3,What are the treatments for Glaucoma ?,"Although open-angle glaucoma cannot be cured, ...",NIHSeniorHealth,Glaucoma
4,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...,NIHSeniorHealth,Glaucoma
...,...,...,...,...
16407,What is (are) Diabetic Neuropathies: The Nerve...,Focal neuropathy appears suddenly and affects ...,NIDDK,Diabetic Neuropathies: The Nerve Damage of Dia...
16408,How to prevent Diabetic Neuropathies: The Nerv...,The best way to prevent neuropathy is to keep ...,NIDDK,Diabetic Neuropathies: The Nerve Damage of Dia...
16409,How to diagnose Diabetic Neuropathies: The Ner...,Doctors diagnose neuropathy on the basis of sy...,NIDDK,Diabetic Neuropathies: The Nerve Damage of Dia...
16410,What are the treatments for Diabetic Neuropath...,The first treatment step is to bring blood glu...,NIDDK,Diabetic Neuropathies: The Nerve Damage of Dia...
16411,What to do for Diabetic Neuropathies: The Nerv...,- Diabetic neuropathies are nerve disorders ca...,NIDDK,Diabetic Neuropathies: The Nerve Damage of Dia...

In [4]:
medquad_df.describe()

,question,answer,source,focus_area
count,16412,16407,16412,16398
unique,14984,15817,9,5126
top,What causes Causes of Diabetes ?,This condition is inherited in an autosomal re...,GHR,Breast Cancer
freq,20,348,5430,53

In [6]:
medquad_df.isna().sum()

question       0
answer         5
source         0
focus_area    14
dtype: int64

In [14]:
medquad_df[medquad_df['answer'].isnull()]

,question,answer,source,focus_area
3591,What is (are) HELLP syndrome ?,NaN,GARD,HELLP syndrome
3840,What is (are) X-linked lymphoproliferative syn...,NaN,GARD,X-linked lymphoproliferative syndrome
4200,What is (are) Familial HDL deficiency ?,NaN,GARD,Familial HDL deficiency
4433,What is (are) Emery-Dreifuss muscular dystroph...,NaN,GARD,"Emery-Dreifuss muscular dystrophy, X-linked"
6693,What is (are) Emery-Dreifuss muscular dystroph...,NaN,GARD,"Emery-Dreifuss muscular dystrophy, dominant type"

In [13]:
medquad_df[medquad_df['question'] == 'What is (are) ?']

Empty DataFrame
Columns: [question, answer, source, focus_area]
Index: []

# Dropping null answers rows.

In [15]:
drop_null_answers_df = medquad_df.dropna(subset=['answer'])

In [17]:
drop_null_answers_df.isna().sum()

question       0
answer         0
source         0
focus_area    14
dtype: int64

In [18]:
drop_null_answers_df

,question,answer,source,focus_area
0,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...,NIHSeniorHealth,Glaucoma
1,What causes Glaucoma ?,"Nearly 2.7 million people have glaucoma, a lea...",NIHSeniorHealth,Glaucoma
2,What are the symptoms of Glaucoma ?,Symptoms of Glaucoma Glaucoma can develop in ...,NIHSeniorHealth,Glaucoma
3,What are the treatments for Glaucoma ?,"Although open-angle glaucoma cannot be cured, ...",NIHSeniorHealth,Glaucoma
4,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...,NIHSeniorHealth,Glaucoma
...,...,...,...,...
16407,What is (are) Diabetic Neuropathies: The Nerve...,Focal neuropathy appears suddenly and affects ...,NIDDK,Diabetic Neuropathies: The Nerve Damage of Dia...
16408,How to prevent Diabetic Neuropathies: The Nerv...,The best way to prevent neuropathy is to keep ...,NIDDK,Diabetic Neuropathies: The Nerve Damage of Dia...
16409,How to diagnose Diabetic Neuropathies: The Ner...,Doctors diagnose neuropathy on the basis of sy...,NIDDK,Diabetic Neuropathies: The Nerve Damage of Dia...
16410,What are the treatments for Diabetic Neuropath...,The first treatment step is to bring blood glu...,NIDDK,Diabetic Neuropathies: The Nerve Damage of Dia...
16411,What to do for Diabetic Neuropathies: The Nerv...,- Diabetic neuropathies are nerve disorders ca...,NIDDK,Diabetic Neuropathies: The Nerve Damage of Dia...

# lowercase entire df

In [19]:
lowercase_df = drop_null_answers_df.applymap(lambda x: x.lower() if isinstance(x, str) else x)

/var/folders/bl/c0pvtpr55y3477p6dl_6s5kh0000gn/T/ipykernel_6645/3527642856.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  lowercase_df = drop_null_answers_df.applymap(lambda x: x.lower() if isinstance(x, str) else x)

In [35]:
lowercase_df[lowercase_df.duplicated(subset=['question', 'answer', 'source', 'focus_area'], keep=False)]

,question,answer,source,focus_area
15243,what is (are) causes of diabetes ?,diabetes is a complex group of diseases with a...,niddk,causes of diabetes
15244,what causes causes of diabetes ?,type 1 diabetes is caused by a lack of insulin...,niddk,causes of diabetes
15245,what causes causes of diabetes ?,type 2 diabetesthe most common form of diabete...,niddk,causes of diabetes
15246,what causes causes of diabetes ?,insulin resistance and beta cell dysfunction\n...,niddk,causes of diabetes
15247,what causes causes of diabetes ?,other types of diabetes have a variety of poss...,niddk,causes of diabetes
...,...,...,...,...
16207,what causes causes of diabetes ?,type 2 diabetesthe most common form of diabete...,niddk,causes of diabetes
16208,what causes causes of diabetes ?,insulin resistance and beta cell dysfunction\n...,niddk,causes of diabetes
16209,what causes causes of diabetes ?,other types of diabetes have a variety of poss...,niddk,causes of diabetes
16210,what causes causes of diabetes ?,other types of diabetes have a variety of poss...,niddk,causes of diabetes
16211,what to do for causes of diabetes ?,- diabetes is a complex group of diseases with...,niddk,causes of diabetes

# dropping dupliacted rows in entire df

In [36]:
drop_duplicated_df = lowercase_df.drop_duplicates(subset=['question', 'answer', 'source', 'focus_area'])

In [ ]:
drop_duplicated_df

,question,answer,source,focus_area
0,what is (are) glaucoma ?,glaucoma is a group of diseases that can damag...,nihseniorhealth,glaucoma
1,what causes glaucoma ?,"nearly 2.7 million people have glaucoma, a lea...",nihseniorhealth,glaucoma
2,what are the symptoms of glaucoma ?,symptoms of glaucoma glaucoma can develop in ...,nihseniorhealth,glaucoma
3,what are the treatments for glaucoma ?,"although open-angle glaucoma cannot be cured, ...",nihseniorhealth,glaucoma
4,what is (are) glaucoma ?,glaucoma is a group of diseases that can damag...,nihseniorhealth,glaucoma
...,...,...,...,...
16407,what is (are) diabetic neuropathies: the nerve...,focal neuropathy appears suddenly and affects ...,niddk,diabetic neuropathies: the nerve damage of dia...
16408,how to prevent diabetic neuropathies: the nerv...,the best way to prevent neuropathy is to keep ...,niddk,diabetic neuropathies: the nerve damage of dia...
16409,how to diagnose diabetic neuropathies: the ner...,doctors diagnose neuropathy on the basis of sy...,niddk,diabetic neuropathies: the nerve damage of dia...
16410,what are the treatments for diabetic neuropath...,the first treatment step is to bring blood glu...,niddk,diabetic neuropathies: the nerve damage of dia...
16411,what to do for diabetic neuropathies: the nerv...,- diabetic neuropathies are nerve disorders ca...,niddk,diabetic neuropathies: the nerve damage of dia...

# removing (are) in “What is (are) Glaucoma ?”

In [40]:
drop_duplicated_df["question"] = drop_duplicated_df["question"].str.replace(r"\(.*?\)", "", regex=True).str.strip()

/var/folders/bl/c0pvtpr55y3477p6dl_6s5kh0000gn/T/ipykernel_6645/325347466.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drop_duplicated_df["question"] = drop_duplicated_df["question"].str.replace(r"\(.*?\)", "", regex=True).str.strip()

In [41]:
drop_duplicated_df

,question,answer,source,focus_area
0,what is glaucoma ?,glaucoma is a group of diseases that can damag...,nihseniorhealth,glaucoma
1,what causes glaucoma ?,"nearly 2.7 million people have glaucoma, a lea...",nihseniorhealth,glaucoma
2,what are the symptoms of glaucoma ?,symptoms of glaucoma glaucoma can develop in ...,nihseniorhealth,glaucoma
3,what are the treatments for glaucoma ?,"although open-angle glaucoma cannot be cured, ...",nihseniorhealth,glaucoma
4,what is glaucoma ?,glaucoma is a group of diseases that can damag...,nihseniorhealth,glaucoma
...,...,...,...,...
16407,what is diabetic neuropathies: the nerve dama...,focal neuropathy appears suddenly and affects ...,niddk,diabetic neuropathies: the nerve damage of dia...
16408,how to prevent diabetic neuropathies: the nerv...,the best way to prevent neuropathy is to keep ...,niddk,diabetic neuropathies: the nerve damage of dia...
16409,how to diagnose diabetic neuropathies: the ner...,doctors diagnose neuropathy on the basis of sy...,niddk,diabetic neuropathies: the nerve damage of dia...
16410,what are the treatments for diabetic neuropath...,the first treatment step is to bring blood glu...,niddk,diabetic neuropathies: the nerve damage of dia...
16411,what to do for diabetic neuropathies: the nerv...,- diabetic neuropathies are nerve disorders ca...,niddk,diabetic neuropathies: the nerve damage of dia...

In [42]:
drop_duplicated_df["answer"] = drop_duplicated_df["answer"].str.strip()

/var/folders/bl/c0pvtpr55y3477p6dl_6s5kh0000gn/T/ipykernel_6645/3061686933.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drop_duplicated_df["answer"] = drop_duplicated_df["answer"].str.strip()

In [62]:

drop_duplicated_df

,question,answer,source,focus_area
0,what is glaucoma ?,glaucoma is a group of diseases that can damag...,nihseniorhealth,glaucoma
1,what causes glaucoma ?,"nearly 2.7 million people have glaucoma, a lea...",nihseniorhealth,glaucoma
2,what are the symptoms of glaucoma ?,symptoms of glaucoma glaucoma can develop in ...,nihseniorhealth,glaucoma
3,what are the treatments for glaucoma ?,"although open-angle glaucoma cannot be cured, ...",nihseniorhealth,glaucoma
4,what is glaucoma ?,glaucoma is a group of diseases that can damag...,nihseniorhealth,glaucoma
...,...,...,...,...
16407,what is diabetic neuropathies: the nerve dama...,focal neuropathy appears suddenly and affects ...,niddk,diabetic neuropathies: the nerve damage of dia...
16408,how to prevent diabetic neuropathies: the nerv...,the best way to prevent neuropathy is to keep ...,niddk,diabetic neuropathies: the nerve damage of dia...
16409,how to diagnose diabetic neuropathies: the ner...,doctors diagnose neuropathy on the basis of sy...,niddk,diabetic neuropathies: the nerve damage of dia...
16410,what are the treatments for diabetic neuropath...,the first treatment step is to bring blood glu...,niddk,diabetic neuropathies: the nerve damage of dia...
16411,what to do for diabetic neuropathies: the nerv...,- diabetic neuropathies are nerve disorders ca...,niddk,diabetic neuropathies: the nerve damage of dia...

In [66]:
drop_duplicated_df["question"] = drop_duplicated_df["question"].str.replace(r"\?\s*\?+", "", regex=True)

/var/folders/bl/c0pvtpr55y3477p6dl_6s5kh0000gn/T/ipykernel_6645/346057433.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drop_duplicated_df["question"] = drop_duplicated_df["question"].str.replace(r"\?\s*\?+", "", regex=True)

In [85]:
drop_duplicated_df.describe()

,question,answer,source,focus_area
count,16359,16359,16359,16345
unique,14345,15817,9,4741
top,what is high blood cholesterol ?,this condition is inherited in an autosomal re...,ghr,breast cancer
freq,19,348,5430,58